(function (App) {
  "use strict";

  const freeze = Object.freeze;

  App.CONSTANTS = freeze({
    references: freeze({
      solarConstantWm2: 1361,
      earthEquilibriumK: 255,
      earthAlbedo: 0.30,
      earthEscapeVelocityKms: 11.2,
      kelvinOffset: 273.15,
      waterTriplePointAtm: 0.006,
    }),
    stars: freeze({
      m: freeze({
        id: "m",
        name: "Representative Active Red Dwarf",
        shortName: "Red Dwarf (M-type)",
        luminosity: 0.04,
        temperatureK: 3300,
        activity: "Elevated",
        lifespan: "Very long",
        orbitMin: 0.08,
        orbitMax: 0.50,
        orbitDefault: 0.20,
        lightColor: "#ff9a63",
      }),
      g: freeze({
        id: "g",
        name: "Sun-Like Star",
        shortName: "Sun-Like (G-type)",
        luminosity: 1.0,
        temperatureK: 5770,
        activity: "Moderate",
        lifespan: "Long",
        orbitMin: 0.50,
        orbitMax: 2.00,
        orbitDefault: 1.00,
        lightColor: "#ffd06a",
      }),
      f: freeze({
        id: "f",
        name: "Hot White-Yellow Star",
        shortName: "Hotter (F-type)",
        luminosity: 2.5,
        temperatureK: 6800,
        activity: "Moderate",
        lifespan: "Shorter",
        orbitMin: 0.80,
        orbitMax: 3.00,
        orbitDefault: 1.58,
        lightColor: "#e8efff",
      }),
    }),
    planet: freeze({
      massMin: 0.5,
      massMax: 3.0,
      massExponent: 0.27,
    }),
    atmosphere: freeze({
      pressureMinUi: 0.10,
      pressureMax: 5.0,
      oxygenMaxPct: 35,
      methaneMaxPct: 2,
      co2OptionsPct: freeze([0, 0.04, 0.1, 1, 5, 20, 50]),
      methaneOptionsPct: freeze([0, 0.0002, 0.01, 0.1, 0.5, 1, 2]),
    }),
    climate: freeze({
      initialTemperatureK: 288,
      minTemperatureK: 150,
      maxTemperatureK: 650,
      maxIterations: 30,
      normalDamping: 0.85,
      oscillationDamping: 0.35,
      strongOscillationDamping: 0.25,
      temperatureToleranceK: 0.1,
      albedoTolerance: 0.001,
      waterVaporCoefficientK: 12,
      albedoMin: 0.08,
      albedoMax: 0.80,
      liquidWaterAlbedo: 0.10,
      rockAlbedo: 0.25,
      iceAlbedo: 0.65,
      atmosphericAlbedoMax: 0.20,
      backgroundGreenhouseK: 24,
      dryGreenhouseMaxK: 120,
      denseCo2MaxK: 60,
      waterVaporPoints: freeze([
        freeze([150, 0]), freeze([250, 0]), freeze([273, 0.20]),
        freeze([288, 0.55]), freeze([310, 1.00]),
        freeze([340, 1.50]), freeze([650, 1.50]),
      ]),
      icePoints: freeze([
        freeze([150, 1]), freeze([243, 1]), freeze([253, 0.80]),
        freeze([263, 0.50]), freeze([273, 0.20]),
        freeze([283, 0]), freeze([650, 0]),
      ]),
      boilingPoints: freeze([
        freeze([0.006, 0.01]), freeze([0.01, 7]), freeze([0.10, 46]),
        freeze([0.50, 81]), freeze([1.00, 100]), freeze([2.00, 120]),
        freeze([5.00, 152]),
      ]),
    }),
    geology: freeze(["Dormant", "Low", "Moderate", "Active", "Extreme"]),
    magneticFields: freeze(["None", "Weak", "Moderate", "Strong"]),
    defaultInputs: freeze({
      planetName: "Nereid-7",
      starType: "m",
      orbitalDistance: 0.22,
      planetMass: 1.2,
      atmosphericPressure: 0.8,
      oxygenPct: 0,
      carbonDioxidePct: 0.1,
      methanePct: 0.01,
      surfaceWaterInventory: 45,
      geologicActivity: "Moderate",
      magneticField: "Weak",
    }),
    earthInputs: freeze({
      planetName: "Earth Reference",
      starType: "g",
      orbitalDistance: 1.0,
      planetMass: 1.0,
      atmosphericPressure: 1.0,
      oxygenPct: 21,
      carbonDioxidePct: 0.04,
      methanePct: 0.0002,
      surfaceWaterInventory: 71,
      geologicActivity: "Moderate",
      magneticField: "Moderate",
    }),
  });
})(window.HabitablePlanet = window.HabitablePlanet || {});
